# Generated by Django 4.2.16 on 2025-12-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category_created_at_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
    ]
